repositories:
  - name: stable
    url: https://charts.helm.sh/stable

context: {{ requiredEnv "K8S_CLUSTER_NAME" }}
   
environments:
  dev:
  int:
  main:
  sprint:
  prod-blue:
  prod-green:
    
releases:
# Single Tier Website
  - name: {{ requiredEnv "PROJECT" }}-{{ requiredEnv "BRANCH" | lower }}
    chart: ../helm/charts/dojo
    values:
      - overrides/dojo/dojo.yaml.gotmpl
    labels:
        category: dts
        app: dojo
        tier: frontend
    namespace: dojo-{{ requiredEnv "BRANCH" | lower }}
    installed: true
    